### ISSUE TITLE
cant load more than 2 match options

### ISSUE THREAD

**Issue by buzz2** [chadsmith/OpenVBX-Plugin-Match#5]
I belong to a group and there is a issue if using hostgator that limits your plugin to 2 match options. When the third is added, the program restarts and goes back to 2 options. Have tried multiple sites on Host gator.

**Comment by jumpfire** [comment]
this isnt just on hostgator...

**Comment by chadsmith** [comment]
I just pushed out a fix.

**Comment by buzz2** [comment]
I removed the old match and installed the new one. Running version 91 openvbx. Installed new mod and still having the same issue. Can not go higher than 2 options or flows. Thanks

**Comment by chadsmith** [comment]
The new version only works with 1.0+ since jQuery was updated.
On Sep 17, 2011 7:10 AM, "buzz2" <
reply@reply.github.com>
wrote:

**Comment by buzz2** [comment]
Thank you very much. It works.
